'use client';

import { useState } from 'react';

interface ShareModalProps {
  planName: string;
  onConfirm: (sharedBy: string) => Promise<void>;
  onClose: () => void;
}

export default function ShareModal({ planName, onConfirm, onClose }: ShareModalProps) {
  const [name, setName] = useState('');
  const [agreed, setAgreed] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async () => {
    if (!agreed) {
      setError('Please confirm this plan was generated by IRunAlone.');
      return;
    }
    setLoading(true);
    setError('');
    try {
      await onConfirm(name.trim() || 'Anonymous Runner');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to share. Please try again.');
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 z-10">
        <h2 className="text-lg font-bold text-slate-900 mb-1">Share to Community</h2>
        <p className="text-sm text-slate-500 mb-5">
          Share <span className="font-medium text-slate-700">{planName}</span> so others can
          discover and download it.
        </p>

        {/* Name input */}
        <label className="block mb-4">
          <span className="text-sm font-medium text-slate-700 mb-1.5 block">
            Your name <span className="text-slate-400 font-normal">(optional)</span>
          </span>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Anonymous Runner"
            maxLength={50}
            className="w-full px-3 py-2.5 rounded-xl ring-1 ring-inset ring-slate-300 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-blue-500 transition"
          />
        </label>

        {/* Checkbox */}
        <label className="flex items-start gap-3 cursor-pointer mb-5 select-none">
          <input
            type="checkbox"
            checked={agreed}
            onChange={(e) => {
              setAgreed(e.target.checked);
              setError('');
            }}
            className="mt-0.5 w-4 h-4 rounded accent-blue-600 flex-shrink-0"
          />
          <span className="text-sm text-slate-600">
            This plan was generated by <span className="font-semibold text-slate-800">WeRunAlone</span> and I consent to sharing it publicly.
          </span>
        </label>

        {/* Error */}
        {error && (
          <p className="text-sm text-red-600 mb-4 bg-red-50 rounded-lg px-3 py-2">{error}</p>
        )}

        {/* Actions */}
        <div className="flex gap-3">
          <button
            onClick={onClose}
            disabled={loading}
            className="flex-1 px-4 py-2.5 rounded-xl ring-1 ring-inset ring-slate-300 text-sm font-medium text-slate-600 hover:bg-slate-50 transition cursor-pointer disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={loading || !agreed}
            className="flex-1 px-4 py-2.5 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 text-white text-sm font-semibold transition cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed hover:from-blue-500 hover:to-purple-500"
          >
            {loading ? 'Sharing…' : '🌍 Share'}
          </button>
        </div>
      </div>
    </div>
  );
}
